// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Identidade.Infraestrutura.Data;

namespace Identidade.Infraestrutura.Migrations
{
    [DbContext(typeof(ARCDbContext))]
    [Migration("20181129015401_FixingPermissionOperations")]
    partial class FixingPermissionOperations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Identidade.Dominio.Modelos.Permission", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new { Id = "acordoscomerciais" },
                        new { Id = "adicionar.composicao" },
                        new { Id = "agenda.financeira" },
                        new { Id = "agendamento.tarefas" },
                        new { Id = "agrupamentos.customizados" },
                        new { Id = "agrupamentos.flexiveis" },
                        new { Id = "ajuste.prudencial" },
                        new { Id = "alterar.embarque.acordo.comercial" },
                        new { Id = "alterar.preco.embarque.acordo.comercial" },
                        new { Id = "alterar.tranche.acordo.comercial" },
                        new { Id = "Analise.Comparativa.Perfis" },
                        new { Id = "analise.exposicao.credito" },
                        new { Id = "analise.fixacoes" },
                        new { Id = "analise.precos.fixacoes" },
                        new { Id = "aplicacaobloqueios" },
                        new { Id = "aplicacaobloqueios.edicao" },
                        new { Id = "aprovacao" },
                        new { Id = "aprovacao.faturamento.pagamento" },
                        new { Id = "aprovacao.faturamento.recebimento" },
                        new { Id = "atualizacao.monetaria" },
                        new { Id = "benchmarks" },
                        new { Id = "bloqueios" },
                        new { Id = "boletagem.alteracao.boletas.terceiros" },
                        new { Id = "boletagem.alteracao.boletas.validadas" },
                        new { Id = "boletagem.exportacao.operacoes" },
                        new { Id = "boletagem.remocao.boletas.terceiros" },
                        new { Id = "cadastra.configuracao.webservice" },
                        new { Id = "cadastro.analitico.customizado" },
                        new { Id = "cadastro.conciliacao.caixa" },
                        new { Id = "cadastro.conciliacao.operacao" },
                        new { Id = "cadastro.modelos.impairment" },
                        new { Id = "cadastro.seguros" },
                        new { Id = "caixa" },
                        new { Id = "calculo.liquidez" },
                        new { Id = "calculo.relatorio.perdas" },
                        new { Id = "calculo.relatorio.regulatorio" },
                        new { Id = "calendarios" },
                        new { Id = "campos.customizados" },
                        new { Id = "carteiras" },
                        new { Id = "cenarios.stress" },
                        new { Id = "cenarios.temporais" },
                        new { Id = "cfar" },
                        new { Id = "classificacao.contabil" },
                        new { Id = "classificadores" },
                        new { Id = "classificar.banking.trading" },
                        new { Id = "composicao.benchmark" },
                        new { Id = "composicao.capital.social" },
                        new { Id = "conciliacao.operacoes" },
                        new { Id = "conciliacao.pagamentos.recebimentos" },
                        new { Id = "configuracao.aprecamento" },
                        new { Id = "configuracao.campos.customizados" },
                        new { Id = "configuracao.criterio.imposto" },
                        new { Id = "configuracao.exposicao" },
                        new { Id = "configuracao.extensibilidade" },
                        new { Id = "configuracao.fluxo.caixa" },
                        new { Id = "configuracao.valor.implicito" },
                        new { Id = "configuracoes.mercadorias.fisicas" },
                        new { Id = "contas" },
                        new { Id = "contas.correntes" },
                        new { Id = "contatos" },
                        new { Id = "controle.custodia" },
                        new { Id = "correcao.taxa" },
                        new { Id = "criterio.aprecamento" },
                        new { Id = "criterio.imposto" },
                        new { Id = "curvas" },
                        new { Id = "custo.medio" },
                        new { Id = "custos.liquidacao" },
                        new { Id = "datacaster" },
                        new { Id = "desaprovacao" },
                        new { Id = "desaprovacao.faturamento.pagamento" },
                        new { Id = "desaprovacao.faturamento.recebimento" },
                        new { Id = "desconsidera.workflow.salvamento.dados.mercado" },
                        new { Id = "deslogar.usuario" },
                        new { Id = "detalhes.analiticos" },
                        new { Id = "dividas" },
                        new { Id = "duration" },
                        new { Id = "dv01" },
                        new { Id = "edicao.arquivos.configuracao" },
                        new { Id = "edicao.correlacao" },
                        new { Id = "edicao.volatilidade" },
                        new { Id = "edita.exportacao.ftp.controller" },
                        new { Id = "edita.exportacao.local.controller" },
                        new { Id = "edita.layouts.integracao.modelo.controller" },
                        new { Id = "editar.boleta.retroativa" },
                        new { Id = "editar.boleta.retroativa.periodo.fechamento.corrente" },
                        new { Id = "editar.composicao" },
                        new { Id = "editar.custo" },
                        new { Id = "editar.lancamentos" },
                        new { Id = "empresas" },
                        new { Id = "empresas.capital.social" },
                        new { Id = "empresas.detentoras" },
                        new { Id = "exclusao.cenario" },
                        new { Id = "execucao.housekeeping" },
                        new { Id = "execucao.trilha.auditoria" },
                        new { Id = "Exercicio.Operacoes" },
                        new { Id = "expectativa.desinvestimento.quantidade" },
                        new { Id = "export.contabil" },
                        new { Id = "exportacao.curvas" },
                        new { Id = "exportacao.itens.diretorio" },
                        new { Id = "exportacao.lancamentos.contabeis" },
                        new { Id = "exportacao.proventos" },
                        new { Id = "exportacao.series" },
                        new { Id = "exportacao.superficies" },
                        new { Id = "exposicao" },
                        new { Id = "exposicao.regulatoria" },
                        new { Id = "exposicao.volumetrica" },
                        new { Id = "expurgo.cenario.credito" },
                        new { Id = "fatores.risco" },
                        new { Id = "filtros" },
                        new { Id = "fixacao.embarques" },
                        new { Id = "fluxosfinanceiros" },
                        new { Id = "fundos" },
                        new { Id = "fundos.abertos" },
                        new { Id = "futuros" },
                        new { Id = "geracao.cenario.credito" },
                        new { Id = "gerar.lancamentos" },
                        new { Id = "gestao.lancamentos" },
                        new { Id = "grafico.contas" },
                        new { Id = "graficos.historicos" },
                        new { Id = "grupos.usuarios" },
                        new { Id = "gv01" },
                        new { Id = "habilita.customizacao.layout" },
                        new { Id = "historico.atividades" },
                        new { Id = "historico.campos" },
                        new { Id = "historico.classificacao.posicao" },
                        new { Id = "historico.composicoes" },
                        new { Id = "historico.contratos" },
                        new { Id = "historico.desinvestimento" },
                        new { Id = "historico.empresas" },
                        new { Id = "historico.reclassificacao.contabil" },
                        new { Id = "Historico.Vinculos" },
                        new { Id = "importacao" },
                        new { Id = "incluir.boleta.retroativa" },
                        new { Id = "incluir.boleta.retroativa.periodo.fechamento.corrente" },
                        new { Id = "incluir.custo" },
                        new { Id = "indicadores.contratos" },
                        new { Id = "indicadores.credito" },
                        new { Id = "indicadores.empresas" },
                        new { Id = "indicadores.performance" },
                        new { Id = "instrucoes.pagamento" },
                        new { Id = "juros.moratorios" },
                        new { Id = "lancamentos.contabeis" },
                        new { Id = "licencas.distribuicao" },
                        new { Id = "licencas.importacao" },
                        new { Id = "limit.manager" },
                        new { Id = "limites.alcada" },
                        new { Id = "logs.resultados" },
                        new { Id = "mapeamento.contas" },
                        new { Id = "margem" },
                        new { Id = "mascara.relatorios" },
                        new { Id = "mercadorias.fisicas" },
                        new { Id = "modelo.caixa" },
                        new { Id = "modelo.cobertura.liquidez" },
                        new { Id = "modelo.controller" },
                        new { Id = "modelo.desinvestimento" },
                        new { Id = "modelo.exposicao.credito" },
                        new { Id = "modelo.liquidez" },
                        new { Id = "modelo.margem" },
                        new { Id = "modelo.risco" },
                        new { Id = "modelos.fluxos.caixa" },
                        new { Id = "modelos.pnl" },
                        new { Id = "moedas" },
                        new { Id = "Movimentacao.Financeira" },
                        new { Id = "opcoes" },
                        new { Id = "operacoes" },
                        new { Id = "participacao.acionaria" },
                        new { Id = "perfil.controller" },
                        new { Id = "perfis" },
                        new { Id = "performanceattribution" },
                        new { Id = "permissao" },
                        new { Id = "permissao.carteiras" },
                        new { Id = "pnl.agregado" },
                        new { Id = "pnl.consolidado" },
                        new { Id = "pnl.diario" },
                        new { Id = "pnl.hipotetico" },
                        new { Id = "pnl.rentabilidade.cotas" },
                        new { Id = "pnl.rentabilidade.timing.contribution" },
                        new { Id = "pnl.rentabilidade.tir" },
                        new { Id = "pode.desconsiderar.alcada.calculos" },
                        new { Id = "portal.administrativo" },
                        new { Id = "posicoes.vista" },
                        new { Id = "prazo.medio" },
                        new { Id = "precificacao.parametrizavel" },
                        new { Id = "produtosestruturados" },
                        new { Id = "programa.hedge" },
                        new { Id = "projecao.contas" },
                        new { Id = "projecao.diferencas.creditos" },
                        new { Id = "quantidadebloqueada" },
                        new { Id = "recalculo.estatisticas" },
                        new { Id = "registro.camara" },
                        new { Id = "registro.eventos" },
                        new { Id = "regra.dado.mercado" },
                        new { Id = "relacoes.inter.company" },
                        new { Id = "relatorio.boletas" },
                        new { Id = "relatorio.calcula" },
                        new { Id = "relatorio.exporta" },
                        new { Id = "relatorio.publica" },
                        new { Id = "relatorio.regulatorio" },
                        new { Id = "relatorio.relacoes.hedge" },
                        new { Id = "relatorio.remove" },
                        new { Id = "relatorio.salva" },
                        new { Id = "relatorios" },
                        new { Id = "remover.boleta.retroativa" },
                        new { Id = "remover.boleta.retroativa.periodo.fechamento.corrente" },
                        new { Id = "remover.composicao" },
                        new { Id = "remover.custo" },
                        new { Id = "reprovacao" },
                        new { Id = "responsabilidade.controller" },
                        new { Id = "risco.backtest" },
                        new { Id = "risco.buscahedge" },
                        new { Id = "rounding.rules" },
                        new { Id = "salvar.analise.desinvestimento" },
                        new { Id = "scripts" },
                        new { Id = "series" },
                        new { Id = "setores.economicos" },
                        new { Id = "split.boleta.ou.liquidacao" },
                        new { Id = "superficies" },
                        new { Id = "swaps" },
                        new { Id = "template.evento" },
                        new { Id = "teste.analise.cenarios" },
                        new { Id = "teste.analise.razao" },
                        new { Id = "teste.regressao" },
                        new { Id = "teste.regressao.prospectivo" },
                        new { Id = "teste.termo.critico" },
                        new { Id = "testes.consolidados" },
                        new { Id = "testes.impairment" },
                        new { Id = "tipos.contrato" },
                        new { Id = "titulos" },
                        new { Id = "tv01" },
                        new { Id = "usuarios" },
                        new { Id = "valida.workflow.dados.mercado" },
                        new { Id = "validacao" },
                        new { Id = "validacao.faturamento.pagamento" },
                        new { Id = "validacao.faturamento.recebimento" },
                        new { Id = "validar.lancamentos" },
                        new { Id = "var.historico" },
                        new { Id = "var.instrumento" },
                        new { Id = "var.parametrico" },
                        new { Id = "var.smc" },
                        new { Id = "var.tve" },
                        new { Id = "Vinculo.Operacao" },
                        new { Id = "visualizacao.cenarios.temporais" },
                        new { Id = "visualizacao.cotas" },
                        new { Id = "visualizacao.curvas" },
                        new { Id = "visualizacao.limit.manager" },
                        new { Id = "visualizacao.serieshistoricas" },
                        new { Id = "visualizacao.superficies" },
                        new { Id = "visualizacaobloqueios" },
                        new { Id = "vp.analise.fluxo.caixa" },
                        new { Id = "vp.gap.analysis" },
                        new { Id = "vp.instrumento" },
                        new { Id = "vp.stresstesting" },
                        new { Id = "vp.vertice" },
                        new { Id = "vv01" },
                        new { Id = "webservice.integracao.analitico.tabular.acesso" },
                        new { Id = "xmapping" }
                    );
                });

            modelBuilder.Entity("Identidade.Dominio.Modelos.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<DateTime>("LastUpdatedAt");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("Name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<bool?>("PasswordDoesNotExpire");

                    b.Property<DateTimeOffset?>("PasswordExpiration");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PasswordHistory");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new { Id = "USR_00000000-0000-0000-0000-000000000000", AccessFailedCount = 0, ConcurrencyStamp = "a8d630bb-25ae-4527-9f4b-b60dd1055b4b", CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), EmailConfirmed = false, LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), LockoutEnabled = false, LockoutEnd = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Name = "Administrator", PasswordHash = "$2b$10$5KLD7QESIcHEh29oLZi3L.3hJUTXehvqmxGstyKbl4w0gg7jOh40e", PasswordHistory = "", PhoneNumberConfirmed = false, TwoFactorEnabled = false, UserName = "admin" }
                    );
                });

            modelBuilder.Entity("Identidade.Dominio.Modelos.UserGroup", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("LastUpdatedAt");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("Identidade.Dominio.Modelos.UserGroupPermission", b =>
                {
                    b.Property<string>("UserGroupId");

                    b.Property<string>("PermissionId");

                    b.Property<int>("PermissionOperations");

                    b.HasKey("UserGroupId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserGroupPermission");
                });

            modelBuilder.Entity("Identidade.Dominio.Modelos.UserGroupUser", b =>
                {
                    b.Property<string>("UserGroupId");

                    b.Property<string>("UserId");

                    b.HasKey("UserGroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGroupUser");
                });

            modelBuilder.Entity("Identidade.Dominio.Modelos.UserSubstitution", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("SubstituteUserId");

                    b.HasKey("UserId", "SubstituteUserId");

                    b.HasIndex("SubstituteUserId");

                    b.ToTable("UserSubstitutions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Identidade.Dominio.Modelos.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Identidade.Dominio.Modelos.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Identidade.Dominio.Modelos.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Identidade.Dominio.Modelos.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Identidade.Dominio.Modelos.UserGroupPermission", b =>
                {
                    b.HasOne("Identidade.Dominio.Modelos.Permission", "Permission")
                        .WithMany("UserGroupPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Identidade.Dominio.Modelos.UserGroup", "UserGroup")
                        .WithMany("UserGroupPermissions")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Identidade.Dominio.Modelos.UserGroupUser", b =>
                {
                    b.HasOne("Identidade.Dominio.Modelos.UserGroup", "UserGroup")
                        .WithMany("UserGroupUsers")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Identidade.Dominio.Modelos.User", "User")
                        .WithMany("UserGroupUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Identidade.Dominio.Modelos.UserSubstitution", b =>
                {
                    b.HasOne("Identidade.Dominio.Modelos.User", "SubstituteUser")
                        .WithMany()
                        .HasForeignKey("SubstituteUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Identidade.Dominio.Modelos.User", "User")
                        .WithMany("UserSubstitutions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
